### ISSUE TITLE
카테고리별 검색 결과 조회 관련 서비스 구현 

### ISSUE THREAD

**Issue by ChoiByungok** [KDT3MiniProjectTeam-7/Mini_Project_BE#22]
## Description(설명)

- 카테고리별 검색 결과 조회 관련 서비스를 구현합니다.

## Tasks(New feature)

- [x] 카테고리별 검색(상품 이름) 결과를 반환한다.
- [x]  한 글자라도 일치 할 시 해당 카테고리의 상품들을 반환한다.
- [x] 한번에 5개의 상품만 출력 될 수 있도록 페이징을 한다.
