### ISSUE TITLE
최근 검색어 서비스 구현

### ISSUE THREAD

**Issue by CocoIsCat** [KDT3MiniProjectTeam-7/Mini_Project_BE#9]
## Description(설명)
- 최근 검색어 서비스를 구현합니다.
## Tasks(New feature)
- [x] 최근 검색어 추가
- [x] 최근 검색어 삭제
- [x] 최근 검색어 전체 삭제
